In [1]:
"""作业：针对mnist数据进行分类， 采用CART决策树"""
import numpy as np
import  pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_digits
from tensorflow.keras.datasets import mnist
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
daigits = load_digits()
data = daigits.data
print(data.shape)
print(data[1])
print(daigits.images[1])
print(daigits.target[1])
X,y = daigits.data.reshape(-1,1),daigits.images.reshape(-1,1)

(1797, 64)
[ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
  3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
 16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
  0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]
[[ 0.  0.  0. 12. 13.  5.  0.  0.]
 [ 0.  0.  0. 11. 16.  9.  0.  0.]
 [ 0.  0.  3. 15. 16.  6.  0.  0.]
 [ 0.  7. 15. 16. 16.  2.  0.  0.]
 [ 0.  0.  1. 16. 16.  3.  0.  0.]
 [ 0.  0.  1. 16. 16.  6.  0.  0.]
 [ 0.  0.  1. 16. 16.  6.  0.  0.]
 [ 0.  0.  0. 11. 16. 10.  0.  0.]]
1


In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

#不采用规范化，查看算法的正确率
tree = DecisionTreeClassifier()
tree.fit(X_train,y_train)
y_pred = tree.predict(X_test)
print(accuracy_score(y_pred,y_test))
print(tree.score(X_train,y_train))
print(tree.score(X_test,y_test))

1.0
1.0
1.0


In [3]:
#规范化处理数据
ss = preprocessing.StandardScaler()
X_train_ss = ss.fit_transform(X_train)
X_test_ss = ss.fit_transform(X_test)
tree = DecisionTreeClassifier()
tree.fit(X_train_ss,y_train)
y_peed = tree.predict(X_test_ss)
print(accuracy_score(y_peed,y_test))

1.0


In [10]:
#网格调参
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
param = {"criterion":["gini","entropy"],
        "max_depth":[10,15]}
gs = GridSearchCV(estimator=DecisionTreeClassifier(),param_grid=param,
                 cv=2,n_jobs=-1,verbose=10,)

gs.fit(X_train,y_train)
print(gs.best_params_)
y_hat = gs.best_estimator_.predict(X_test)
print(classification_report(y_test,y_hat))

Fitting 2 folds for each of 4 candidates, totalling 8 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   8 | elapsed:    2.7s remaining:    8.3s
[Parallel(n_jobs=-1)]: Done   3 out of   8 | elapsed:    2.7s remaining:    4.6s
[Parallel(n_jobs=-1)]: Done   4 out of   8 | elapsed:    2.7s remaining:    2.7s
[Parallel(n_jobs=-1)]: Done   5 out of   8 | elapsed:    2.8s remaining:    1.6s
[Parallel(n_jobs=-1)]: Done   6 out of   8 | elapsed:    2.8s remaining:    0.9s
[Parallel(n_jobs=-1)]: Done   8 out of   8 | elapsed:    2.8s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done   8 out of   8 | elapsed:    2.8s finished


{'criterion': 'gini', 'max_depth': 15}
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     14106
         1.0       1.00      1.00      1.00      1014
         2.0       1.00      1.00      1.00       818
         3.0       1.00      1.00      1.00       717
         4.0       1.00      1.00      1.00       846
         5.0       1.00      1.00      1.00       707
         6.0       1.00      1.00      1.00       611
         7.0       1.00      1.00      1.00       680
         8.0       1.00      1.00      1.00       858
         9.0       1.00      1.00      1.00       646
        10.0       1.00      1.00      1.00       667
        11.0       1.00      1.00      1.00       732
        12.0       1.00      1.00      1.00       920
        13.0       1.00      1.00      1.00       835
        14.0       1.00      1.00      1.00       872
        15.0       1.00      1.00      1.00      1036
        16.0       1.00      1.00      1.0